HW-3
SicParv1sMagna/KTSGitClient pull request #1
Opened 2024-04-21 16:00 UTC by SicParv1sMagna

2024-04-21 17:18 UTC, Christik requested changes
Тимур, у тебя хорошо получается, продолжай в том же духе))

Обозначение комментариев:

[!!!] - серьезная проблема в коде, влияющая на функциональность проекта или ломающая ее, которую необходимо поправить
[!] - важное замечание, которое необходимо поправить
[?] - вопрос по реализации, на который надо ответить, но править необязательно
[+] - предложение, возможное улучшение, которое править необязательно

2024-04-21 17:18 UTC, Christik commented on src/components/icons/ArrowDownIcon/ArrowDownIcon.tsx
> +  } else fillColor = '#000000';
[!] Этот код дублируется. Точно такой же есть в `CheckIcon`. Я бы посоветовала вынести эту логику в Icon и использовать стили для определения цветов.

В `Icon` тогда будет что-то типа:

```ts
return (
    <svg
        className={cn(
            styles.icon,
            styles[`icon_${color}`]
        )}
        // ...
    >
    //...
```

В Icon.modules.scss будет что-то типа:
```scss
.icon {
    color: #000000; // цвет лучше вынести в константы

    &_accent {
        color: #518581; // цвет лучше вынести в константы
    }

    &_secondary {
        color: #AFADB5; // цвет лучше вынести в константы
    }
}
```

А у `path` тогда заливку будет `fill="currentColor"`

2024-04-21 17:18 UTC, Christik commented on src/components/Button/Button.tsx
> +import './styles.scss';
[!] По заданию нужно использовать css modules: `import styles from './Button.mobules.scss'`

2024-04-21 17:18 UTC, Christik commented on src/pages/MainPage/MainPage.tsx
> +    if (repos.length !== 0) localStorage.setItem('repos', JSON.stringify(repos));
[!] Эту логику лучше поместить в `useEffect` и указать список зависимостей, иначе этот код будет отрабатывать при каждом рендере компонента

2024-04-21 17:18 UTC, Christik commented on src/pages/MainPage/components/PaginatedItems.tsx
> +    console.log(repos, children);
[+] Обычно консоль логи удаляем из кода)

2024-04-21 17:18 UTC, Christik commented on src/pages/MainPage/components/PaginatedItems.tsx
> +    }
[!] Если передаем колбэк в качестве пропса в дочерний компонент, то для оптимизации лучше использовать `useCallback()`

2024-04-21 17:42 UTC, SicParv1sMagna commented on src/components/Button/Button.tsx
> +  var btnClass = classNames({
поправлено

2024-04-21 17:42 UTC, SicParv1sMagna commented on src/components/Button/Button.tsx
> +  let { loading, children, onClick, disabled, className, ...other } = props;
Поправлено

2024-04-21 17:43 UTC, SicParv1sMagna commented on src/components/Button/Button.tsx
> +      className={`${btnClass} ${className}`}
поправлено

2024-04-21 17:44 UTC, SicParv1sMagna commented on src/pages/MainPage/components/PaginatedItems.tsx
> +    }
поправлено

2024-04-21 17:45 UTC, SicParv1sMagna commented on src/pages/MainPage/components/PaginatedItems.tsx
> +    console.log(repos, children);
поправлено

2024-04-21 17:46 UTC, SicParv1sMagna commented on src/pages/MainPage/MainPage.tsx
> +    if (repos.length !== 0) localStorage.setItem('repos', JSON.stringify(repos));
поправлено

2024-04-21 19:21 UTC, SicParv1sMagna commented on src/components/constants.css
> +  --border-radius: 0;
поправил

2024-04-21 19:21 UTC, SicParv1sMagna commented on src/components/Button/styles.scss
> +button {
поправлено

2024-04-21 19:22 UTC, SicParv1sMagna commented on src/components/Button/styles.scss
> +  &.btn-disabled {
поправлено

2024-04-21 19:22 UTC, SicParv1sMagna commented on src/components/Button/styles.scss
> +  //border-bottom-color: var(--button-primary-text);
убрал

2024-04-21 19:25 UTC, SicParv1sMagna commented on src/components/Button/Button.tsx
> +export default Button;
поправил

2024-04-21 20:26 UTC, SicParv1sMagna commented on src/components/Button/Button.tsx
> +import './styles.scss';
поправил

2024-04-21 20:33 UTC, SicParv1sMagna commented on src/components/icons/ArrowDownIcon/ArrowDownIcon.tsx
> +  } else fillColor = '#000000';
поправил

2024-04-22 03:51 UTC, Christik commented on src/components/Button/Button.tsx
> +      )}
[!] Сорри, неправильно тебе подсказала в этом месте)) Смотри, нам нужно использовать scss modules. Мы импортируем объект `styles` и классы используем из этого объекта:

```ts
className={cn(
    className,
    styles.btn
    loading && styles.btn_loading,
    disabled && styles.btn_disabled,
)}
```

2024-04-22 03:53 UTC, Christik commented on src/components/Button/styles.module.scss
> +@import "../constants.module.scss";
[+] Константы можно было оставить без module.

2025-02-02 22:42 UTC, closed without merging